"""delete column

Revision ID: 840da1f6257c
Revises: f783df2b2fda
Create Date: 2025-01-31 20:49:22.692953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '840da1f6257c'
down_revision: Union[str, None] = 'f783df2b2fda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Products', 'certification')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Products', sa.Column('certification', sa.UUID(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
