"""delete colmn in certification table

Revision ID: 85cc01119da9
Revises: db90a5b3b321
Create Date: 2025-01-31 20:53:01.074590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85cc01119da9'
down_revision: Union[str, None] = 'db90a5b3b321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Certifications_name_key', 'Certifications', type_='unique')
    op.drop_column('Certifications', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Certifications', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('Certifications_name_key', 'Certifications', ['name'])
    # ### end Alembic commands ###
