"""add certification table

Revision ID: f783df2b2fda
Revises: 878fc70ffb19
Create Date: 2025-01-31 20:47:29.908232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f783df2b2fda'
down_revision: Union[str, None] = '878fc70ffb19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Products', sa.Column('certification', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Products', 'certification')
    # ### end Alembic commands ###
